// eslint-disable-next-line
export const capitalizeFirstLetter = string => string.charAt(0).toUpperCase() + string.slice(1);

export const languageMap = {
  en: 'English',
  cn: 'Chinese',
  tr: 'Turkish',
  sv: 'Swedish',
  ru: 'Russian',
  pt: 'Portuguese',
  ko: 'Korean',
  ja: 'Japanese',
  it: 'Italian',
  hi: 'Hindi',
  fr: 'French',
  fi: 'Finnish',
  es: 'Spanish',
  de: 'Deutsch',
  ab: 'Abkhazian',
  af: 'Afrikaans',
  ar: 'Arabic',
  bn: 'Bengali',
  bs: 'Bosnian',
  cs: 'Czech',
  da: 'Danish',
  el: 'Greek',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  he: 'Hebrew',
  hu: 'Hungarian',
  id: 'Indonesian',
  la: 'Latin',
  mk: 'Macedonian',
  ml: 'Malayalam',
  nb: 'Norwegian Bokmål',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  ro: 'Romanian',
  sh: 'Serbo-Croatian',
  sr: 'Serbian',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tl: 'Tagalog',
  uk: 'Ukrainian',
  zh: 'Old Chinese',
};
